[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

# SPA: rediriger toutes les routes vers index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
